spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/serverdb
    username: ############
    password: ############
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect:
        format_sql: true
    show-sql: true